# Generated by Django 5.2.8 on 2025-12-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_producto_pedido_perfilcliente_detallepedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservas",
                to="reservas.producto",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservas.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="direccion_destino",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="direccion_origen",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="tipo_servicio",
            field=models.CharField(max_length=50),
        ),
    ]
