# Generated by Django 5.2.8 on 2025-11-28 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField()),
                ("lugar", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conferencia", "Conferencia"),
                            ("concierto", "Concierto"),
                            ("seminario", "Seminario"),
                        ],
                        max_length=50,
                    ),
                ),
                ("es_privado", models.BooleanField(default=False)),
                (
                    "asistentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="eventos_asistidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_organizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
